### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by DavidusEdwardus** [robn/nginx#1]
Just a standard build with -
# ./configure --with-mail

gives -

src/mail/ngx_mail_xmpp_handler.c:43:15: error: ‘xmpp_starttls_proceed’ defined but not used [-Werror=unused-variable]
cc1: all warnings being treated as errors
make[1]: **\* [objs/src/mail/ngx_mail_xmpp_handler.o] Error 1

Halp !

**Comment by robn** [comment]
Yep, compiler doesn't like redundant code when compiling without TLS. Thanks!
