### ISSUE TITLE
XEP-0163: Personal Eventing Protocol

### ISSUE THREAD

**Issue by ghost** [robn/nginx#4]
Hi Rob,
Sorry if this isn't the right place to ask, but does Fastmail support [XEP-0163](https://xmpp.org/extensions/xep-0163.html)? The reason I ask is because it's needed for [OMEMO](http://conversations.im/omemo/) support, an upcoming encryption method that is potentially better than OTR. I'm looking into purchasing Fastmail service and this would be a big plus.
Thanks.

**Comment by robn** [comment]
No, we don't support PEP. Our server is very old, and doesn't support much of anything made in the last five years (but of course will still happily pass stanzas). We're still deciding what we want to do with our XMPP support, if anything, so I have no plans to share with you at this time.

**Comment by ghost** [comment]
Thank you for this information.
