### ISSUE TITLE
Question and config example request

### ISSUE THREAD

**Issue by cryptofuture** [robn/nginx#5]
As you know nginx support dynamic modules quite a time already. And my idea is to backport xmmp support from nginx-xmmp to last stable nginx-mail module. But I'm not familiar with ngx_mail_core module, through this is not a problem. Main question is nginx-xmmp will be able to communicate with xmpp server with ECC ciphers suites encryption. 

```
EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256
and sect571k1 curve 
```

This should be not a problem ether, since nginx ciphers suites support quite epic, but as I understand you used it djabberd without encryption in local network, but I want to use it for proxying to xmmp server located in another place physically.  
Also config example will be welcome, if you have one, should save me some time.

**Comment by cryptofuture** [comment]
Was able to [backport](https://github.com/cryptofuture/nginx-hda-bundle/tree/master/debian/patches) module. Playing with configuration now.

```
mail {
    xmpp_auth ip:5222; # tried servername here too
    # server already have ssl support, but I want use ngx_xmpp as proxy.
    proxy on;

    server {
    protocol xmpp;
    server_name xmmp.me;
    ssl on;
    ssl_certificate /etc/nginx/ssl/site.crt;
    ssl_certificate_key /etc/nginx/ssl/site.key;
    ssl_ciphers "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305";
    ssl_ecdh_curve sect571r1;
    ssl_protocols TLSv1.1 TLSv1.2;
    ssl_session_timeout 5m;
    ssl_session_tickets on;
   }
 server {
    protocol xmpp;
    server_name xmmp2.me;
    ssl on;
    ssl_certificate /etc/nginx/ssl/site.crt;
    ssl_certificate_key /etc/nginx/ssl/site.key;
    ssl_ciphers "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384";
    ssl_ecdh_curve sect571r1;
    ssl_protocols TLSv1.1 TLSv1.2;
    ssl_session_timeout 5m;
    ssl_session_tickets on;
   }
}

```

I tried as ip and as servername with and without port? and with extra `/` at the end, can't figure out xmpp_auth format. Will be very good if give some simple config example.
P.S.: Ciphers shown here as example, I usually use two xmpp hostnames, one with strict, but poor ciphers support, and second more compatible with another servers.

**Comment by robn** [comment]
Sorry I missed this; it appears I lost or never received the notification email.

I've added some more docs to README.md. Briefly though, looking at your config:

* `xmpp_auth` is for specifying the auth mechanisms you want, eg `PLAIN`, `LOGIN`, etc. (just like the `imap_auth` directive). You instead want `auth_http` to point to your auth service, and your auth service will return the backend server IP:port to proxy to.
* Your `server` blocks don't list ports to listen on.
* You probably want `starttls on` or `starttls only` on port 5222; `ssl on` is for "wrappermode" or "SSL-first" operation, like you'd find on port 5223.

I'm going to close this issue now. Pretty much all of this is actually about general nginx mail configuration, not specific to the XMPP patches.

**Comment by cryptofuture** [comment]
Thx, for the reply. Will give nginx-xmpp another try in next free time.
